using System.Collections.Generic;
using System.Text;

namespace AchReactive.EditorTools
{
    /// <summary>
    /// 타입 정의로부터 도메인 데이터 클래스와 CSV 매퍼의 C# 소스를 생성한다.
    /// UI 와 분리된 순수 문자열 생성 로직이라 테스트하기 쉽다.
    /// </summary>
    public static class DataTypeCodeWriter
    {
        public const string Namespace = "AchReactive.Generated";

        /// <summary>데이터 클래스 소스(예: MonsterData.cs).</summary>
        public static string WriteData(string typeName, string baseType, IList<DataFieldDef> fields)
        {
            string cls = typeName + "Data";
            string baseSpec = string.IsNullOrEmpty(baseType) ? "EntityData" : baseType;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated> AchReactive Type Designer 가 생성한 파일입니다. 직접 수정하면 재생성 시 덮어쓰입니다.");
            sb.AppendLine("using System;");
            sb.AppendLine();
            sb.AppendLine($"namespace {Namespace}");
            sb.AppendLine("{");
            sb.AppendLine($"    [Serializable]");
            sb.AppendLine($"    public class {cls} : {baseSpec}");
            sb.AppendLine("    {");
            if (fields != null)
            {
                foreach (DataFieldDef f in fields)
                {
                    if (f == null || string.IsNullOrEmpty(f.name))
                        continue;
                    sb.AppendLine($"        public {DataFieldTypeMap.CSharp(f.type)} {f.name};");
                }
            }
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        /// <summary>CSV 매퍼 소스(예: MonsterCsvMapper.cs).</summary>
        public static string WriteCsvMapper(string typeName, IList<DataFieldDef> fields)
        {
            string cls = typeName + "Data";
            string mapper = typeName + "CsvMapper";

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated> AchReactive Type Designer 가 생성한 파일입니다. 직접 수정하면 재생성 시 덮어쓰입니다.");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Globalization;");
            sb.AppendLine("using AchReactive;");
            sb.AppendLine();
            sb.AppendLine($"namespace {Namespace}");
            sb.AppendLine("{");
            sb.AppendLine($"    public sealed class {mapper} : ICsvMapper<{cls}>");
            sb.AppendLine("    {");
            sb.AppendLine($"        public {cls} Map(IReadOnlyDictionary<string, string> row)");
            sb.AppendLine("        {");
            sb.AppendLine($"            var d = new {cls}();");
            sb.AppendLine("            d.id = Get(row, \"id\");");
            if (fields != null)
            {
                foreach (DataFieldDef f in fields)
                {
                    if (f == null || string.IsNullOrEmpty(f.name))
                        continue;
                    sb.AppendLine($"            d.{f.name} = {ParseExpr(f.type, f.name)};");
                }
            }
            sb.AppendLine("            return d;");
            sb.AppendLine("        }");
            sb.AppendLine();
            AppendHelpers(sb);
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string ParseExpr(DataFieldType t, string field)
        {
            string cell = $"Get(row, \"{field}\")";
            switch (t)
            {
                case DataFieldType.String: return cell;
                case DataFieldType.Int: return $"ParseInt({cell})";
                case DataFieldType.Float: return $"ParseFloat({cell})";
                case DataFieldType.Bool: return $"ParseBool({cell})";
                case DataFieldType.StringArray: return $"SplitStr({cell})";
                case DataFieldType.IntArray: return $"SplitInt({cell})";
                case DataFieldType.FloatArray: return $"SplitFloat({cell})";
                default: return cell;
            }
        }

        private static void AppendHelpers(StringBuilder sb)
        {
            sb.AppendLine("        private static string Get(IReadOnlyDictionary<string, string> row, string key) =>");
            sb.AppendLine("            row.TryGetValue(key, out var v) ? v : string.Empty;");
            sb.AppendLine();
            sb.AppendLine("        private static int ParseInt(string s) =>");
            sb.AppendLine("            int.TryParse(s, NumberStyles.Integer, CultureInfo.InvariantCulture, out var v) ? v : 0;");
            sb.AppendLine();
            sb.AppendLine("        private static float ParseFloat(string s) =>");
            sb.AppendLine("            float.TryParse(s, NumberStyles.Float, CultureInfo.InvariantCulture, out var v) ? v : 0f;");
            sb.AppendLine();
            sb.AppendLine("        private static bool ParseBool(string s) =>");
            sb.AppendLine("            bool.TryParse(s, out var v) && v;");
            sb.AppendLine();
            sb.AppendLine("        private static string[] SplitStr(string s) =>");
            sb.AppendLine("            string.IsNullOrEmpty(s) ? new string[0] : s.Split('|');");
            sb.AppendLine();
            sb.AppendLine("        private static int[] SplitInt(string s)");
            sb.AppendLine("        {");
            sb.AppendLine("            var parts = SplitStr(s);");
            sb.AppendLine("            var r = new int[parts.Length];");
            sb.AppendLine("            for (int i = 0; i < parts.Length; i++) r[i] = ParseInt(parts[i]);");
            sb.AppendLine("            return r;");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private static float[] SplitFloat(string s)");
            sb.AppendLine("        {");
            sb.AppendLine("            var parts = SplitStr(s);");
            sb.AppendLine("            var r = new float[parts.Length];");
            sb.AppendLine("            for (int i = 0; i < parts.Length; i++) r[i] = ParseFloat(parts[i]);");
            sb.AppendLine("            return r;");
            sb.AppendLine("        }");
        }
    }
}
